name: flutter_stripe
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+4
  flutter_redux: ^0.5.3
  redux_thunk: ^0.2.1
  redux_logging: ^0.3.0
  badges: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
